#!/bin/bash

function add_ip_addr(){ ip=$1;ansible-playbook -i $HOME/hosts $HOME/add_ip.yml --tags "add" --extra-vars ip=$ip; }
function add_ip_addr_rabbit(){ ip=$1;ansible-playbook -i $HOME/hosts $HOME/add_ip.yml --tags "add,add_rabbitmq" --extra-vars ip=$ip; }

[ "$1" ] || { echo -e "\e[00;31mplease specify address\e[00m"; exit 1; };

if [[ $EUID -ne 1002 ]] ; then
   echo "This script must be run from deploy user"
   exit 1
else
   if [[ $2 == "-r" ]] ; then
   	add_ip_addr_rabbit $1
   else
	add_ip_addr $1
   fi
fi
