#!/bin/bash

LINE_NUMBER=""
IP=$2
PORT=$3
DEF_PORT="3306"
IPT="/sbin/iptables"

function save_rules()
{
	service iptables save
}

function usage()
{
	echo -e "\n\nUsage:\nadd_ip [option] [IP] [port (optional, 3306 by default)]\noption:\n\t-a\t\tto add IP address with specified port (or 3306 by default)\n\t-d\t\tto remove IP address with specified port (or 3306 by default)"
}

function valid_ip()
{
    local  ip=$1
    local  stat=1

    if [[ $ip =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
        OIFS=$IFS
        IFS='.'
        ip=($ip)
        IFS=$OIFS
        [[ ${ip[0]} -le 255 && ${ip[1]} -le 255 \
            && ${ip[2]} -le 255 && ${ip[3]} -le 255 ]]
        stat=$?
    fi
    return $stat
}

function valid_port()
{
    local  port=$1
    local  stat=1

    if [[ $port =~ ^[0-9]{1,5}$ ]]; then
        [[ ${port[0]} -le 65535 ]]
        stat=$?
    fi
    return $stat
}

[ "$1" ] || { echo -e "\e[00;31mplease specify option\e[00m `usage`"; exit 1; };
[ "$2" ] || { echo -e "\e[00;31mplease specify address\e[00m `usage`"; exit 1; };
[ "$3" ] || { PORT=$DEF_PORT; };

echo -n "check address $IP ... "
if valid_ip $IP; then echo -e "\e[00;32m[GOOD]\e[00m"; else echo -e "\e[00;31m[BAD]\e[00m `usage`";exit 1; fi
echo -n	"check port $PORT ... "
if valid_port $PORT; then echo -e "\e[00;32m[GOOD]\e[00m"; else echo -e "\e[00;31m[BAD]\e[00m `usage`";exit 1; fi

if [ $1 == "-a" ]; then
	echo -n "adding..."
	LINE_NUMBER=`$IPT -L INPUT -n --line-numbers|awk -v r=$PORT '$8 == "dpt:"r'|awk {'print $1'}|sed -n '$p'`
	if [ -z $LINE_NUMBER ]; then
		$IPT -I INPUT 11 -p tcp -s $IP -m tcp --dport $PORT -j ACCEPT
	else
		$IPT -I INPUT $LINE_NUMBER  -p tcp -s $IP -m tcp --dport $PORT -j ACCEPT
	fi
	echo -e "\e[00;32m[DONE]\e[00m"
	save_rules
elif [ $1 == "-d" ]; then
	echo -n "delete..."
	LINE_NUMBER=`$IPT -L INPUT -n --line-numbers|awk -v r=$IP '$5 == r'|awk -v r=$PORT '$8 == "dpt:"r'|awk {'print $1'}|sed -n '$p'`
	if [ -z $LINE_NUMBER ];then
		echo -e "\e[00;31m[FAIL]\nspecified IP is not mentioned in the INPUT chain rules\e[00m `usage`"
	else
		$IPT -D INPUT $LINE_NUMBER
		echo -e "\e[00;32m[DONE]\e[00m"
		save_rules
	fi
else
	echo -ne "\e[00;31mplease specify option\e[00m"
	usage
	exit 1
fi
